# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6299234ed50b31cfb3745439f91ed651"
name = "ALLCARTAIPLUGIN"
handle = "allcartaiplugin"
application_url = "https://principle-identify-thomson-logan.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://principle-identify-thomson-logan.trycloudflare.com/auth/callback", "https://principle-identify-thomson-logan.trycloudflare.com/auth/shopify/callback", "https://principle-identify-thomson-logan.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
